"""Added a slug field to RoomModel

Revision ID: 41cf6ea245d0
Revises: c64828253ec3
Create Date: 2025-02-01 20:46:17.732475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cf6ea245d0'
down_revision: Union[str, None] = 'c64828253ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'rooms', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'slug')
    # ### end Alembic commands ###
