"""refactor a user and room relationships

Revision ID: c64828253ec3
Revises: 18ddb8b33e24
Create Date: 2025-02-01 01:32:25.293201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64828253ec3'
down_revision: Union[str, None] = '18ddb8b33e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rooms', ['current_room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_room_id')
    # ### end Alembic commands ###
