from .user_dependencies import get_user_service
from .room_dependencies import get_room_service, get_room_by_slug
from .genre_dependencies import get_genre_service, get_genre_by_slug
from .actor_dependencies import get_actor_by_id, get_actor_service